version: '3'

networks:
  my_network2:
    driver: bridge

volumes:
  volume_postgres:

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: dosidb
      POSTGRES_USER: hassan
      POSTGRES_PASSWORD: hassan
    ports:
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    networks:
      - my_network2

  spring-app:
    image:  hboutinkhar/spring-app
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dosidb
      SPRING_DATASOURCE_USERNAME: hassan
      SPRING_DATASOURCE_PASSWORD: hassan
    networks:
      - my_network2

